version: "3.7"

services:
  php:
    container_name: comments-php
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - otus-lesson-microservices

  nginx:
    container_name: comments-nginx
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    depends_on:
      - php
    ports:
      - "8001:80"
    volumes:
      - "./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./public:/var/www/html/public"
    networks:
      - otus-lesson-microservices

  mysql:
    container_name: comments-mysql
    image: mysql:5.7.35
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: otus
      MYSQL_USER: ${DB_USERNAME:-comments}
      MYSQL_PASSWORD: ${DB_PASSWORD:-comments}
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_ROOT_HOST: "%"
    volumes:
      - otus-lesson-mysql-data:/var/lib/mysql
    networks:
      - otus-lesson-microservices

volumes:
  otus-lesson-mysql-data: { }

networks:
  otus-lesson-microservices: